//
//  HomeInteractor.swift
//  iMarvel
//
//  Created by Karim Sakr on 04/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol HomeBusinessLogic {
    
    func fetchCharacterList(completion: @escaping () -> Void)
    
    func getCharacters() -> [HomeModels.ViewModels.Character]
    
}

protocol HomeDataStore {
    var characters: [HomeModels.ViewModels.Character] { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    
    var presenter: HomePresentationLogic?
    
    var characters: [HomeModels.ViewModels.Character] = [HomeModels.ViewModels.Character]()
    
    private var bag = DisposeBag()
    
    func getCharacters() -> [HomeModels.ViewModels.Character] {
        return characters
    }
    
    func fetchCharacterList(completion: @escaping () -> Void) {
        APIClient.shared.request(.fetchCharacterList)
            .subscribe { [weak self] (event:Result<Response<[Character]>, Error>) in
                switch event{
                case .success(let data):
                    self?.characters = self?.presenter?.didGetCharacters(data) ?? []
                    completion()
                case .failure(let error):
                    print(error.localizedDescription)
                }
            }.disposed(by: bag)
    }
}
