//
//  HomeViewController.swift
//  iMarvel
//
//  Created by Karim Sakr on 04/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import RxCocoa

protocol HomeDisplayLogic: AnyObject {
    
    func showError(error: Error)
}

class HomeViewController: UIViewController, HomeDisplayLogic {
    
    var interactor: HomeBusinessLogic?
    var router: HomeRouter?
    
    private var bag = DisposeBag()
    
    private lazy var searchController: UISearchController = {
       let search = UISearchController(searchResultsController: nil)
        search.obscuresBackgroundDuringPresentation = false
        search.searchBar.placeholder = "Search character..."
        return search
    }()
    
    private lazy var collectionView: UICollectionView = {
        let layout = UICollectionViewFlowLayout()
        layout.scrollDirection = .vertical
        layout.minimumLineSpacing = 1
        layout.minimumInteritemSpacing = 1
        layout.sectionInset = UIEdgeInsets(top: 0, left: 1, bottom: 0, right: 1)
        let size = (view.width - 4) / 2
        layout.itemSize = CGSize(width: size, height: size)
        
        let collection = UICollectionView(frame: .zero, collectionViewLayout: layout)
        collection.register(CharacterCardCollectionViewCell.self, forCellWithReuseIdentifier: CharacterCardCollectionViewCell.identifier)
        collection.alwaysBounceVertical = true
        collection.showsVerticalScrollIndicator = false
        collection.translatesAutoresizingMaskIntoConstraints = false
        return collection
    }()
    
    private lazy var activityIndicator: UIActivityIndicatorView = {
        let activityIndicator = UIActivityIndicatorView(style: .large)
        activityIndicator.hidesWhenStopped = true
        activityIndicator.translatesAutoresizingMaskIntoConstraints = false
        return activityIndicator
    }()
    
}

//MARK: - Lifecycle
extension HomeViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        setupViews()
        setupNavigationBar()
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        NSLayoutConstraint.activate([
            
            //collectionView constarints
            collectionView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            collectionView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            collectionView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            collectionView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            
            // Activity Indicator constraints
            activityIndicator.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            activityIndicator.centerYAnchor.constraint(equalTo: view.centerYAnchor),
        ])
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        guard let interactor = interactor else { return }
        guard let router = router else { return }
        if !interactor.isUserLoggedIn() {
            router.goToLoginScreen()
        }
    }
}

//MARK: - setup
extension HomeViewController {
    
    private func setup() {
        let viewController = self
        let interactor = HomeInteractor()
        let presenter = HomePresenter()
        let router = HomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setupViews() {
        
        collectionView.delegate = self
        collectionView.dataSource = self
        
        view.addSubview(self.activityIndicator)
        view.addSubview(collectionView)
        
        activityIndicator.isHidden = false
        activityIndicator.startAnimating()
        
    }
    
    private func setupNavigationBar() {
        navigationItem.rightBarButtonItem = UIBarButtonItem(image: UIImage(systemName: "rectangle.portrait.and.arrow.forward"), style: .plain, target: self, action: #selector(logOutButtonTapped))

        navigationItem.searchController = searchController
        searchController.searchBar
            .rx
            .text
            .orEmpty
            .throttle(.milliseconds(500), scheduler: MainScheduler.instance)
            .distinctUntilChanged()
            .subscribe { [unowned self] (query) in
                guard let interactor = interactor else { return }
                guard let element = query.event.element else { return }
                if element.isEmpty {
                    self.fetchCharacters()
                } else {
                    interactor.fetchCharactersByName(skip: 0, limit: 20, name: element) {
                        self.collectionView.reloadData()
                    }
                }
            }.disposed(by: bag)
    }
}

//MARK: - functions
extension HomeViewController {
    
    func fetchCharacters() {
        guard let interactor = interactor else { return }
        interactor.fetchCachedCharacterList {
            self.collectionView.reloadData()
            self.activityIndicator.isHidden = true
        }
    }
    func showError(error: Error) {
        AppSnackBar.make(in: self.view, message: "Something went wrong", duration: .infinite).setAction(with: "Retry") {
            guard let interactor = self.interactor else { return }
            interactor.refreshList {
                self.collectionView.reloadData()
            }
        }.show()
    }
    
    @objc func logOutButtonTapped() {
        guard let interactor = interactor else { return }
        guard let router = router else { return }
        interactor.logOut()
        router.goToLoginScreen()
    }
}

extension HomeViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return interactor!.getCharacters().count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: CharacterCardCollectionViewCell.identifier, for: indexPath) as? CharacterCardCollectionViewCell else {
            fatalError("Failed to dequeue CharacterCardCollectionViewCell in HomeViewController")
        }
        
        cell.configure(with: interactor!.getCharacters()[indexPath.item])
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath) {
        guard let searchBarText = searchController.searchBar.text else { return }
        guard let interactor = interactor else { return }
        if searchBarText.isEmpty {
            interactor.fetchCharacterIfNeeded(index: indexPath.item) {
                collectionView.reloadData()
            }
        } else {
            interactor.fetchCharacterIfNeeded(withName: searchBarText, index: indexPath.item) {
                collectionView.reloadData()
            }
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        
        router?.goToDetailsVC(collectionView, didSelectItemAt: indexPath)
    }
}
