//
//  DetailsPresenter.swift
//  iMarvel
//
//  Created by Karim Sakr on 06/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsPresentationLogic {
    func didGetCharacters(_ model: Response<[Character]>) -> DetailsModels.ViewModels.Character
}

class DetailsPresenter: DetailsPresentationLogic {
    weak var viewController: DetailsDisplayLogic?
    
    func didGetCharacters(_ model: Response<[Character]>) -> DetailsModels.ViewModels.Character {
        guard model.code == 200, let characters = model.data.results else {
            return DetailsModels.ViewModels.Character(name: "", id: "", thumbnailUrl: "", desription: "")
        }
        
        guard let character = characters.first else { return DetailsModels.ViewModels.Character(name: "", id: "", thumbnailUrl: "", desription: "") }
        
        return DetailsModels.ViewModels.Character(name: character.name,
                                                  id: String(character.id),
                                                  thumbnailUrl: character.thumbnail.path + "." + character.thumbnail.ext,
                                                  desription: character.description)
    }
}
