//
//  LoginInteractor.swift
//  iMarvel
//
//  Created by Karim Sakr on 08/04/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
  
}

protocol LoginDataStore {
  //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore {
  var presenter: LoginPresentationLogic?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: LoginModels.Request) {
    
    
  }
}
